import { DefaultTheme } from 'styled-components';


export const theme: DefaultTheme = {
  color: {
    hsbc: {
      content: {
        on_dark_01: '#FFFFFF',
        on_light_01: '#333333',
      },
      rag: {
        green_success: '#00847F',
        red_error: '#A8000B',
        blue_neutral: '#305A85',
        blue_tint_neutral: '#EBEFF4',
        green_tint_success: '#E5F2F2',
        amber_tint_warning: '#FFF8EA',
        red_tint_error: '#F9F2F3',
        amber_warning: '#FFBB33',
      },
      brand: {
        o01_hsbc_red: '#DB0011',
        o02_black: '#000000',
        o03_white: '#FFFFFF',
        o04_light_pearl: '#F3F3F3',
        o05_pearl: '#EDEDED',
        o06_silver: '#D7D8D6',
        o07_pewter: '#767676',
        o08_charcoal: '#333333',
      },
      interaction_default: {
        o05: '#DB0011',
        o06: '#AF000D',
        o07: '#83000A',
      },
      data_visualisation: {
        o01_dusk_pearl: '#6D8EA6',
        o02_jade: '#14A5AB',
        o03_emerald: '#4FA62F',
        o04_amber: '#E67310',
        o05_ruby: '#D71E8D',
        o06_iolite: '#834EFF',
        o07_sapphire: '#2580DC',
        o08_dark_pearl: '#4D6474',
        o09_dark_jade: '#008580',
        o10_dark_emerald: '#34880F',
        o11_dark_amber: '#BF610F',
        o12_dark_ruby: '#A8166D',
        o13_dark_iolite: '#6637D5',
        o14_dark_sapphire: '#1564B5',
      },
    },
    cmb: {
      interaction_default: {
        o01: '#FFFFFF',
        o02: '#F1F3F4',
        o03: '#E4E8EA',
        o04: '#C9D0D5',
        o05: '#4D6474',
        o06: '#3E505D',
        o07: '#1D262C',
      },
      sub_brand: {
        o01_light_slate: '#4D6474',
        o02_slate: '#3E505D',
        o03_dark_slate: '#253038',
        o04_corporate_slate: '#1D262C',
      },
      interaction_defined: {
        o01: '#FFFFFF',
        o02: '#EBF5F5',
        o03: '#D9EDEC',
        o04: '#B2DAD8',
        o05: '#005E59',
        o06: '#004F4B',
        o07: '#00847F',
      },
    },
  },

  typography: {
    m2: {
      headline: {
        headline1: {
          fontSize: 96,
          fontFamily: 'Univers Next for HSBC W29 Rg',
          paragraphIndent: 0,
          paragraphSpacing: 0,
          fontWeight: 400,
          letterSpacing: '-1.5px',
          lineHeight: '112px',
        },
        headline2: {
          fontSize: 60,
          fontFamily: 'Univers Next for HSBC W29 Rg',
          paragraphIndent: 0,
          paragraphSpacing: 0,
          fontWeight: 400,
          letterSpacing: '-0.5px',
          lineHeight: '72px',
        },
        headline3: {
          fontSize: 48,
          fontFamily: 'Univers Next for HSBC W29 Rg',
          paragraphIndent: 0,
          paragraphSpacing: 0,
          fontWeight: 400,
          letterSpacing: '0px',
          lineHeight: '56px',
        },
        headline4: {
          fontSize: 34,
          fontFamily: 'Univers Next for HSBC W29 Rg',
          paragraphIndent: 0,
          paragraphSpacing: 0,
          fontWeight: 500,
          letterSpacing: '0px',
          lineHeight: '36px',
        },
        headline5: {
          fontSize: 24,
          fontFamily: 'Univers Next for HSBC W29 Rg',
          paragraphIndent: 0,
          paragraphSpacing: 0,
          fontWeight: 400,
          letterSpacing: '0.18000000715255737px',
          lineHeight: '24px',
        },
        headline6: {
          fontSize: 20,
          fontFamily: 'Univers Next for HSBC W29 Rg',
          paragraphIndent: 0,
          paragraphSpacing: 0,
          fontWeight: 400,
          letterSpacing: '0.15000000596046448px',
          lineHeight: '24px',
        },
        subtitle1: {
          fontSize: 16,
          fontFamily: 'Univers Next for HSBC W29 Rg',
          paragraphIndent: 0,
          paragraphSpacing: 0,
          fontWeight: 400,
          letterSpacing: '0.15000000596046448px',
          lineHeight: '24px',
        },
        subtitle2: {
          fontSize: 14,
          fontFamily: 'Univers Next for HSBC W29 Rg',
          paragraphIndent: 0,
          paragraphSpacing: 0,
          fontWeight: 400,
          letterSpacing: '0.10000000149011612px',
          lineHeight: '24px',
        },
      },
      body: {
        body1: {
          fontSize: 16,
          fontFamily: 'Univers Next for HSBC W29 Rg',
          paragraphIndent: 0,
          paragraphSpacing: 0,
          fontWeight: 400,
          letterSpacing: '0.5px',
          lineHeight: '24px',
        },
        body2: {
          fontSize: 14,
          fontFamily: 'Univers Next for HSBC W29 Rg',
          paragraphIndent: 0,
          paragraphSpacing: 0,
          fontWeight: 400,
          letterSpacing: '0.25px',
          lineHeight: '20px',
        },
        caption: {
          fontSize: 12,
          fontFamily: 'Univers Next for HSBC W29 Rg',
          paragraphIndent: 0,
          paragraphSpacing: 0,
          fontWeight: 400,
          letterSpacing: '0.4000000059604645px',
          lineHeight: '16px',
        },
        overline: {
          fontSize: 10,
          fontFamily: 'Univers Next for HSBC W29 Rg',
          paragraphIndent: 0,
          paragraphSpacing: 0,
          fontWeight: 400,
          letterSpacing: '1.5px',
          lineHeight: '16px',
        },
        divider1: {
          fontSize: 14,
          fontFamily: 'Univers Next for HSBC W29 Thin',
          paragraphIndent: 0,
          paragraphSpacing: 0,
          fontWeight: 400,
          letterSpacing: '0px',
          lineHeight: '20px',
        },
        divider2: {
          fontSize: 14,
          fontFamily: 'Univers Next for HSBC W29 Thin',
          paragraphIndent: 0,
          paragraphSpacing: 9,
          fontWeight: 400,
          letterSpacing: '0px',
          lineHeight: '18px',
        },
        divider3: {
          fontSize: 12,
          fontFamily: 'Univers Next for HSBC W29 Thin',
          paragraphIndent: 0,
          paragraphSpacing: 8,
          fontWeight: 400,
          letterSpacing: '0px',
          lineHeight: '16px',
        },
      },
      label: {
        medium: {
          fontSize: 14,
          fontFamily: 'Univers Next for HSBC W29 Rg',
          paragraphIndent: 0,
          paragraphSpacing: 0,
          fontWeight: 400,
          letterSpacing: '0px',
          lineHeight: 'normal',
        },
        small: {
          fontSize: 12,
          fontFamily: 'Univers Next for HSBC W29 Rg',
          paragraphIndent: 0,
          paragraphSpacing: 8,
          fontWeight: 400,
          letterSpacing: '0px',
          lineHeight: '16px',
        },
        large: {
          fontSize: 16,
          fontFamily: 'Univers Next for HSBC W29 Rg',
          paragraphIndent: 0,
          paragraphSpacing: 0,
          fontWeight: 400,
          letterSpacing: '0px',
          lineHeight: '24px',
        },
      },
    },
    sys: {
      large: {
        fontSize: 124,
        fontFamily: 'Roboto, sans-serif',
        paragraphIndent: 0,
        paragraphSpacing: 0,
        fontWeight: 600,
        letterSpacing: '1.5px',
        lineHeight: 'normal',
      },
      medium: {
        fontSize: 96,
        fontFamily: 'Roboto, sans-serif',
        paragraphIndent: 0,
        paragraphSpacing: 0,
        fontWeight: 600,
        letterSpacing: '1.5px',
        lineHeight: 'normal',
      },
      small: {
        fontSize: 24,
        fontFamily: 'Roboto, sans-serif',
        paragraphIndent: 0,
        paragraphSpacing: 0,
        fontWeight: 400,
        letterSpacing: '0px',
        lineHeight: '32px',
      },
      xsmall: {
        fontSize: 18,
        fontFamily: 'Roboto, sans-serif',
        paragraphIndent: 0,
        paragraphSpacing: 0,
        fontWeight: 400,
        letterSpacing: '0%',
        lineHeight: '24px',
      },
    },
  },
  media: {
    superLarge: `(min-width: 1400px)`,
    extraLarge: `(min-width: 1200px)`,
    large: '(max-width: 992px)',
    medium: '(max-width: 768px)',
    small: '(max-width: 576px)',
  },
  transition: {
    all: 'all 0.3s ease-in-out',
    height: 'height 0.3s ease-in-out',
    width: 'width 0.3s ease-in-out',
    transform: 'transform 0.3s ease-in-out',
    background: 'background 0.3s ease-in-out',
    color: 'color 0.3s ease-in-out',
    opacity: 'opacity 0.3s ease-in-out',
    border: 'border 0.3s ease-in-out',
  },
};
